### ISSUE TITLE
Comparison w/ MeteoGroup/jbrotli

### ISSUE THREAD

**Issue by sirthias** [nixxcode/jvm-brotli#32]
This project looks awesome but, as a prospective user, I'd be interested in your take on https://github.com/MeteoGroup/jbrotli, which looks like it is (or was) trying to solve the same problem, but appears to be somewhat unmaintained.

Have you looked at MeteoGroup/jbrotli?
How does this project differ from it?
Are there any trade-offs to be aware of?

**Comment by nixxcode** [comment]
The basic concept of Jvm-Brotli is the same as that of JBrotli, which is why the author of that project is credited in the foot of the readme.

The most notable differences are:

1) I've uploaded Jvm-Brotli to Maven central, making it available without needing to specify a 3rd party repository.

2) Java code for encoder/decoder and JNI bindings is taken direct from the Google/Brotli, whereas JBrotli still uses its own outdated (and buggy) Java code. The very reason I created this project was because the stream encoder/decoder in JBrotli kept crashing and I found it completely unusable.

3) As far as trade-offs, the only downside of Jvm-Brotli I am aware of, is that it doesn't support ARM processors yet, meaning a lot of mobile devices won't be supported at the moment. I do still plan to add support in the near future, but JBrotli already has this, as far as I'm aware.

Hope this helps! If you have further questions, just reply. :)

**Comment by sirthias** [comment]
Awesome! All this sounds great, thank you!
So I'll happily jump on your library here and report any problems I might find.
(Also, I'm going to try to get this project a bit more of the attention it deserves... ;)

**Comment by nixxcode** [comment]
Thank you, I appreciate the encouragement and the feedback!

This is my first proper (non-learning) project, so I still feel some cold feet and impostor syndrome, which is why I haven't put more effort into marketing and exposure myself.

Not the easiest feelings to get over, even when one has the best intentions, so your support is deeply appreciated.

**Comment by sirthias** [comment]
Don't worry, you are doing great!
As long as you remain at least somewhat responsive here there is nothing that can go wrong.
No marketing required. :)
