### ISSUE TITLE
Tag releases (and push the tags)

### ISSUE THREAD

**Issue by sirthias** [nixxcode/jvm-brotli#33]
It's good practice to tag all commits that serve as the basis for published artifacts.
This way it's easy to see exactly which state of the project a release is based on and which commits are still unreleased.
Also, github nicely shows a list of all releases on the "Releases" tab... :)

**Comment by nixxcode** [comment]
Thank you for the heads up on that. I really appreciate the help since this is my first proper (non-learning) Github project and all this is still new to me.

I will look into it and apply the proper tagging. Would it be worth doing this for the current release still, before I do further updates? Also, would you have any particular resource (article/tutorial) that I can refer to for best practices on this before I just google it?

Again, many thanks! :)

**Comment by sirthias** [comment]
According to [maven central](https://search.maven.org/search?q=g:com.nixxcode.jvmbrotli%20AND%20a:jvmbrotli&core=gav) you've already published three releases. So the easiest thing is to simply tag the respective commits with

- `git tag -a v0.1.0 <commit-hash>`
- `git tag -a v0.1.1 <commit-hash>`
- `git tag -a v0.2.0 <commit-hash>`

and then

- `git push --tags`

This should take care of everything up to now.
And then, whenever you publish a new release, repeat the process for that specific release.

**Comment by nixxcode** [comment]
Thank you for this, extremely helpful.

I've tagged 0.1.1 and 0.2.0.

I skipped 0.1.0 because it was a botched release.

Will tag future releases accordingly 👍
